### PR TITLE
Add ExternalDependency and IndirectCall

### PR DESCRIPTION
**Pull request by Quincunx271**
I use FetchContent quite a bit, but there's still quite a bit of boilerplate with having to write something like the following:

```cmake
FetchContent_Declare(
  googletest
  GIT_REPOSITORY https://github.com/google/googletest.git
  GIT_TAG        release-1.8.0
)

FetchContent_GetProperties(googletest)
if(NOT googletest_POPULATED)
  FetchContent_Populate(googletest)
  add_subdirectory(${googletest_SOURCE_DIR} ${googletest_BINARY_DIR})
endif()
```

Thus, I wrote ExternalDependency.cmake ("creative" name, I know) to reduce the boilerplate:

```cmake
external_dependency(
  googletest
  GIT_REPOSITORY https://github.com/google/googletest.git
  GIT_TAG        release-1.8.0
)
```

Customization of the code to run on populating can be handled with `ON_POPULATE` and `WITH_ARGS`:

```cmake
# Example from the documentation comment:
function(make_headeronly_library name libname)
  add_library(${libname} INTERFACE)
  target_include_directories(${libname}
    INTERFACE
      "${${name}_SOURCE_DIR}/include"
  )
endfunction()

external_dependency(
  dependency
  URL https://example.org/path/to/dependency
  ON_POPULATE make_headeronly_library
  WITH_ARGS "some_library"
)

# When populating, this is equivalent to:
add_library(some_library INTERFACE)
target_include_directories(some_library
  INTERFACE
    "${dependency_SOURCE_DIR}/include"
)
```

This `ON_POPULATE` arg requires an indirect call of calling a function whose name is stored in a string, hence IndirectCall.cmake.

I have a couple concerns with IndirectCall. As background, `indirect_call(name args...)` works by writing `_indirect_call.cmake` with the code `name(args...)`, then `include`ing that file:

* It's racy. If multiple cmake instances run concurrently on the same binary directory, they can easily overwrite the file used to make the call before they have a chance to include the file. I don't know if this is a problem that is worth considering. I believe `file(LOCK ...)` can solve this problem, but I would need advice on how to properly apply that. The actual function call is simple enough, but I don't know whether just the `file(LOCK ...)` is needed for CMake to respect the lock, and I don't know if there are other things to consider.
* This racy behavior is a potential vulnerability. A malicious user could quickly overwrite the `_indirect_call.cmake` file with arbitrary CMake code which would then be `include`d by `indirect_call(...)`. I don't know if this is a valid concern, however, since it's actions occurring on the user's own machine, but it concerns me nonetheless. `file(LOCK ...)` does nothing to help this, as the malicious user doesn't need to respect the lock.

----

I'm also mildly concerned over licensing, as CMakeCM currently has no license file.

### CODE REVIEW

**Comment by Quincunx271** [comment]
After thinking about it, I don't think the vulnerability does anything meaningful. If an attacker could write to `_indirect_call.cmake`, they've already won. Unless the user runs `sudo cmake`, in which case that's their problem.

The racy behavior can be partially avoided by using `CMAKE_CURRENT_BINARY_DIR` instead of `CMAKE_BINARY_DIR`, or by mangling the arguments into the filename. However, I don't think racy behavior is that worrying to begin with. I don't think many users run multiple instances of cmake concurrently.

**Comment by Quincunx271** [comment]
CMake 3.14 will have a [`FetchContent_MakeAvailable`][fcma], which obviates the need for this:

```cmake
FetchContent_Declare(
  googletest
  GIT_REPOSITORY https://github.com/google/googletest.git
  GIT_TAG        release-1.8.0
)
FetchContent_MakeAvailable(googletest)
```

  [fcma]: https://cmake.org/cmake/help/git-stage/module/FetchContent.html#command:fetchcontent_makeavailable

**Comment by vector-of-bool** [comment]
Sorry that I never addressed this. Busy with so many little things, and my Inbox gets backed up, especially with GitHub emails.

**Comment by Quincunx271** [comment]
No need to apologize, it's totally fine.

**Pull request closed without merging**
